# Generated by Django 2.0.7 on 2020-10-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('음료', '음료'), ('음식', '음식'), ('생활용품', '생활용품'), ('기타', '기타')], default='기타', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(default='2020-10-01 10:10', verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default='https://www.google.co.kr/', verbose_name='group purchase product url'),
        ),
    ]
