# Generated by Django 2.0.7 on 2020-10-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201001_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='제품명을 입력하세요.', max_length=200),
        ),
    ]
