# Generated by Django 2.0.7 on 2020-10-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deadline',
        ),
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(default='https://www.google.co.kr/', verbose_name='출처'),
        ),
    ]
