# Generated by Django 3.1.2 on 2020-10-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201007_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=300, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='secret',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(null=True, verbose_name='출처'),
        ),
    ]
