# Generated by Django 3.1.2 on 2020-10-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201017_2155'),
        ('main', '0005_auto_20201017_1709'),
    ]

    operations = [
    ]
