# Generated by Django 3.1.1 on 2020-10-06 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20201007_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('is_read', models.CharField(default='읽지 않음', max_length=10)),
                ('content', models.TextField()),
                ('scount', models.IntegerField(default=0)),
                ('rcount', models.IntegerField(default=0)),
                ('post', models.ForeignKey(default='존재하지 않는 글', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.post')),
                ('sender', models.ForeignKey(default='알 수 없음', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
