# Generated by Django 2.0.7 on 2020-10-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_read',
            field=models.CharField(default='읽지 않음', max_length=10),
        ),
    ]
