# Generated by Django 2.0.7 on 2020-10-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_renote'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='renotes_r',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='renotes_s',
            field=models.IntegerField(default=0),
        ),
    ]
