# Generated by Django 3.1.2 on 2020-10-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_20201018_2040'),
        ('note', '0003_auto_20201007_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post'),
        ),
    ]
