# Generated by Django 3.1.1 on 2020-10-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
